# File generated by kdevelop's qmake manager.
# ------------------------------------------
# Subdirectory related to the main project directory:.
# The goal is a subdirectory of the project

include(src/compilationtype.pri)

SUBDIRS += src
!official_release:SUBDIRS += tests
TEMPLATE = subdirs
CONFIG += warn_on \
          qt \
          thread \
          ordered
